### ISSUE TITLE
Catalan language is missing test definition

### ISSUE THREAD

**Issue by evilaliv3** [EvanHahn/HumanizeDuration.js#58]
@EvanHahn: as shown by unit test implemented in https://github.com/EvanHahn/HumanizeDuration.js/pull/55 the Catalan language is missing its test definition.

    evilaliv3@remotehost:~/Devel/HumanizeDuration.js$ node_modules/mocha/bin/mocha 

    assert.js:92
      throw new assert.AssertionError({
            ^
    AssertionError: ["ar","da","de","en","es","fr","hu","it","ja","ko","nl","nob","pl","pt","ru","sv","tr","zh-CN","zh-TW"] == ["ar","ca","da","de","en","es","fr","hu","it","ja","ko","nl","nob","pl","pt","ru","sv","tr","zh-CN","zh-TW"]
      at Suite.<anonymous> (/home/evilaliv3/Devel/HumanizeDuration.js/test/get-supported-languages.coffee:17:10)
      at context.describe.context.context (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/mocha/lib/interfaces/bdd.js:49:10)
      at Object.<anonymous> (/home/evilaliv3/Devel/HumanizeDuration.js/test/get-supported-languages.coffee:8:1)
      at Object.<anonymous> (/home/evilaliv3/Devel/HumanizeDuration.js/test/get-supported-languages.coffee:1:1)
      at Module._compile (module.js:456:26)
      at Object.loadFile (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
      at Module.load (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/evilaliv3/Devel/HumanizeDuration.js/node_modules/mocha/lib/mocha.js:192:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/mocha/lib/mocha.js:189:14)
      at Mocha.run (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/mocha/lib/mocha.js:422:31)
      at Object.<anonymous> (/home/evilaliv3/Devel/HumanizeDuration.js/node_modules/mocha/bin/_mocha:398:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:906:3

**Comment by evilaliv3** [comment]
i've added test cases in commit: https://github.com/evilaliv3/HumanizeDuration.js/commit/87e56223490d21a917879306e41a8949d756fd6f

It will be possible to close this issue when merging: https://github.com/EvanHahn/HumanizeDuration.js/pull/55

**Comment by EvanHahn** [comment]
Closed by 87e56223490d21a917879306e41a8949d756fd6f.
